version: "3.9"
services:
  app:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/so5?createDatabaseIfNotExist=true
  db:
    container_name: db
    image: 'mysql:8.0.29'
    environment:
      - MYSQL_ROOT_PASSWORD=so5
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10