spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/so5?createDatabaseIfNotExist=true
    username: root
    password: so5
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/so5/protocol/openid-connect/certs

aws:
  server:
    host: http://localhost:4566
    region: us-east-1
  bucket: so5

imagemagick:
  path: /usr/local/Cellar/imagemagick/7.1.0-33/bin
  resize: 300

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://db:3306/so5?createDatabaseIfNotExist=true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/so5/protocol/openid-connect/certs

aws:
  server:
    host: http://localstack:4566

imagemagick:
  path: /usr/bin